name: testando github actions

on:
  push:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: 'checkout do código'
        uses: actions/checkout@v2
        
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: echo 'foi realizado o checkout do código'